[project]
name = "soundcloud-sync-me"
version = "0.1.0"
description = "sync local with soundcloud account"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "pydantic-settings>=2.12.0",
    "ruff>=0.15.0",
]
